export const FACE_STATES = ["idle", "listening", "thinking", "speaking", "success", "error", "sleeping", "wake"];

export const SKIN_LABELS = {
  GlassWaterSkin: "Glass Water",
  WireRobotHeadSkin: "Wire Robot Head",
  OrganicBlobSkin: "Organic Blob",
  DeployedOrbSkin: "Deployed Orb",
};

const stateMods = {
  idle: {},
  listening: { speed: 1.25, glow: 1.1, pulse: 1.1 },
  thinking: { speed: 1.45, wrinkle: 1.25, movement: 1.25 },
  speaking: { speed: 1.6, glow: 1.35, pulse: 1.65 },
  success: { glow: 1.45, color: "#8dffbf" },
  error: { speed: 1.9, glow: 1.5, color: "#ff3158", glitch: 0.55 },
  sleeping: { speed: 0.35, glow: 0.55, pulse: 0.4, opacity: 0.42 },
  wake: { speed: 1.8, glow: 1.6, pulse: 1.85 },
};

function withStates(base, mapper) {
  return Object.fromEntries(FACE_STATES.map((state) => [state, mapper({ ...base }, stateMods[state] || {}, state)]));
}

export function createDefaultFacePresets() {
  return {
    version: 1,
    activeSkin: "GlassWaterSkin",
    activeState: "idle",
    productionConfigPath: "face/config/face-presets.json",
    global: {
      cameraDistance: 5.8,
      cameraHeight: 0.18,
    },
    skins: {
      GlassWaterSkin: withStates({
        glassOpacity: 0.42,
        glassRoughness: 0.08,
        transmission: 0.92,
        ior: 1.45,
        waterWrinkleStrength: 0.16,
        waterWrinkleScale: 2.8,
        waterAnimationSpeed: 0.55,
        particleCount: 90,
        particleSpeed: 0.8,
        particleSize: 0.035,
        particleColor: "#00ff88",
        particleGlowIntensity: 1.8,
        overallBloomIntensity: 1.0,
        spotlight1Color: "#ffffff",
        spotlight1Intensity: 3.4,
        spotlight1PositionX: -2.4,
        spotlight1PositionY: 2.3,
        spotlight1PositionZ: 3.4,
        spotlight2Color: "#8fdcff",
        spotlight2Intensity: 2.2,
        spotlight2PositionX: 2.5,
        spotlight2PositionY: -1.6,
        spotlight2PositionZ: 2.8,
      }, (base, mod) => ({
        ...base,
        glassOpacity: mod.opacity ?? base.glassOpacity,
        waterWrinkleStrength: base.waterWrinkleStrength * (mod.wrinkle || 1),
        waterAnimationSpeed: base.waterAnimationSpeed * (mod.speed || 1),
        particleSpeed: base.particleSpeed * (mod.speed || 1),
        particleColor: mod.color || base.particleColor,
        particleGlowIntensity: base.particleGlowIntensity * (mod.glow || 1),
        overallBloomIntensity: base.overallBloomIntensity * (mod.glow || 1),
        spotlight1Intensity: base.spotlight1Intensity * (mod.glow || 1),
        spotlight2Intensity: base.spotlight2Intensity * (mod.glow || 1),
      })),
      WireRobotHeadSkin: withStates({
        wireframeColor: "#00ff66",
        wireframeIntensity: 1.45,
        eyeColor: "#ffffff",
        eyeEmissiveIntensity: 2.4,
        headRotationSpeed: 0.35,
        eyePulseSpeed: 1.2,
        panelMovementAmount: 0.06,
        panelMovementSpeed: 0.9,
        glitchAmount: 0,
        speakingPulseAmount: 0.12,
      }, (base, mod, state) => ({
        ...base,
        wireframeColor: mod.color || base.wireframeColor,
        wireframeIntensity: base.wireframeIntensity * (mod.glow || 1),
        eyePulseSpeed: base.eyePulseSpeed * (mod.pulse || 1),
        headRotationSpeed: base.headRotationSpeed * (mod.speed || 1),
        panelMovementSpeed: base.panelMovementSpeed * (mod.speed || 1),
        glitchAmount: state === "error" ? mod.glitch || 0.55 : 0,
        speakingPulseAmount: state === "speaking" ? 0.2 : base.speakingPulseAmount,
      })),
      OrganicBlobSkin: withStates({
        blobColor: "#00ff66",
        translucency: 0.62,
        roughness: 0.34,
        displacementStrength: 0.22,
        displacementScale: 2.6,
        movementSpeed: 0.62,
        pulseMinDisplacementPercent: 0,
        pulsePeakDisplacementPercent: 100,
        pulsePeakDisplacementStrength: 0.34,
        pulseSpeed: 1.15,
        pulseSharpness: 1.8,
        spotlight1Color: "#d8fff0",
        spotlight1Intensity: 3.2,
        spotlight1PositionX: -2.2,
        spotlight1PositionY: 2.1,
        spotlight1PositionZ: 3.2,
        spotlight2Color: "#4bff8d",
        spotlight2Intensity: 2.3,
        spotlight2PositionX: 2.4,
        spotlight2PositionY: -1.7,
        spotlight2PositionZ: 2.6,
      }, (base, mod) => ({
        ...base,
        blobColor: mod.color || base.blobColor,
        translucency: mod.opacity ?? base.translucency,
        displacementStrength: base.displacementStrength * (mod.movement || mod.wrinkle || 1),
        pulsePeakDisplacementStrength: base.pulsePeakDisplacementStrength * (mod.movement || mod.wrinkle || 1),
        movementSpeed: base.movementSpeed * (mod.speed || 1),
        pulseSpeed: base.pulseSpeed * (mod.speed || 1),
        spotlight1Intensity: base.spotlight1Intensity * (mod.glow || 1),
        spotlight2Intensity: base.spotlight2Intensity * (mod.glow || 1),
      })),
      DeployedOrbSkin: withStates({
        orbColor: "#00ff66",
        coreColor: "#ffffff",
        opacity: 1,
        displacementStrength: 1,
        noiseScale: 3.2,
        animationSpeed: 1,
        pulseAmount: 0.35,
        ringIntensity: 1,
        gridIntensity: 1,
      }, (base, mod) => ({
        ...base,
        orbColor: mod.color || base.orbColor,
        opacity: mod.opacity ?? base.opacity,
        displacementStrength: base.displacementStrength * (mod.wrinkle || mod.movement || 1),
        noiseScale: base.noiseScale * (mod.movement || 1),
        animationSpeed: base.animationSpeed * (mod.speed || 1),
        pulseAmount: base.pulseAmount * (mod.pulse || 1),
        ringIntensity: base.ringIntensity * (mod.glow || 1),
        gridIntensity: base.gridIntensity * (mod.glow || 1),
      })),
    },
  };
}

export const defaultFacePresets = createDefaultFacePresets();
